project_id = "iocopqawhvffnerdeaqk"

[functions.b3-quotes]
verify_jwt = false

[functions.exchange-rates]
verify_jwt = false

[functions.generate-social-content]
verify_jwt = false

[functions.buffer-publish]
verify_jwt = false